Homework1
made-mlops-2022/trubachev_mikhail pull request #1
Opened 2022-11-10 12:25 UTC by maikdonut

added homework1

2022-12-05 07:48 UTC, nickdndev commented
![image](https://user-images.githubusercontent.com/49230518/205582047-f835a48a-fa0b-4471-bdff-e8a2948c0009.png)
питон кеш не должен попадать в мастер ветку, надо добавить гит игнор

2022-12-05 07:49 UTC, nickdndev commented
надо добавить самооценку

2022-12-05 07:53 UTC, nickdndev requested changes

2022-12-05 07:53 UTC, nickdndev commented on project/tests/test_train_pred.py
> +    train_pipeline(train_pipeline_params)
need to check mdoel metrics

2022-12-05 11:43 UTC, maikdonut commented on project/tests/test_train_pred.py
> +    train_pipeline(train_pipeline_params)
Model metrics check added

2022-12-05 11:58 UTC, maikdonut commented
### HW1
### Основная часть:

- [x] В пулл-реквесте проведена самооценка, распишите по каждому пункту выполнен ли критерий или нет и на сколько баллов(частично или полностью) (1 балл)

- [x] Выполнено EDA, закоммитьте ноутбук в папку с ноутбуками (1 балл) Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы)
Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл)

- [x] Написана функция/класс для тренировки модели, вызов оформлен как утилита командной строки, записана в readme инструкцию по запуску (3 балла)

- [x] Написана функция/класс predict (вызов оформлен как утилита командной строки), которая примет на вход артефакт/ы от обучения, тестовую выборку (без меток) и запишет предикт по заданному пути, инструкция по вызову записана в readme (3 балла)

- [x] Проект имеет модульную структуру (2 балла)

- [x] Использованы логгеры (2 балла)

- [x] Написаны тесты на отдельные модули и на прогон обучения и predict (3 балла)

- [x] Для тестов генерируются синтетические данные, приближенные к реальным (2 балла)

- [x] Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла)

- [x] Используются датаклассы для сущностей из конфига, а не голые dict (2 балла)

- [ ] Напишите кастомный трансформер и протестируйте его (3 балла) https://towardsdatascience.com/pipelines-custom-transformers-in-scikit-learn-the-step-by-step-guide-with-python-code-4a7d9b068156

- [ ] В проекте зафиксированы все зависимости (1 балл)

- [ ] Настроен CI для прогона тестов, линтера на основе github actions (3 балла). Пример с пары: https://github.com/demo-ml-cicd/ml-python-package

2022-12-15 22:07 UTC, nickdndev commented
![image](https://user-images.githubusercontent.com/49230518/207977279-5d3af940-5cd5-48b2-a557-20e651fcaaab.png)
.idea тоже не должно попадать в мастер

2022-12-15 22:08 UTC, nickdndev commented
итог:22

2022-12-15 22:08 UTC, nickdndev approved these changes

2022-12-16 07:39 UTC, merged